version: '3.6'

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - './backend:/usr/src/app'
            - '/usr/src/app/node_modules'
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        depends_on:
          - mysql


    frontend:
        stdin_open: true
        build:
            context: ./frontend
            dockerfile: Dockerfile
        volumes:
            - './frontend:/usr/src/app'
            - '/usr/src/app/node_modules'
        environment:
            - NODE_ENV=development
        depends_on:
            - backend

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: 'image_optimiser'
            # So you don't have to use root, but you can if you like
            MYSQL_USER: 'remote'
            # You can use whatever password you like
            MYSQL_PASSWORD: 'password'
            # Password for root access
            MYSQL_ROOT_PASSWORD: 'password'
        volumes:
        - './database:/var/lib/mysql'
        ports:
            - 3305:3306

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - 80:80
        depends_on:
            - backend
            - frontend
