version: '3.6'

services:
    backend-testing:
        restart: unless-stopped
        build:
            context: ./backend
            dockerfile: Dockerfile-testing
        volumes:
            - './backend:/usr/src/app'
            - '/usr/src/app/node_modules'
        environment:
            - NODE_ENV=testing
        depends_on:
            - mysql

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: "${DATABASE_NAME}"
            MYSQL_USER: "${DATABASE_USER}"
            MYSQL_PASSWORD: "${DATABASE_PASSWORD}"
            MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD}"
        volumes:
            - './database:/var/lib/mysql'
        ports:
            - 3307:3306

    frontend-testing:
        restart: unless-stopped
        build:
            context: ./frontend
            dockerfile: Dockerfile-testing
        environment:
            - NODE_ENV=production
        depends_on:
            - backend-testing
        ports:
            - "80:80"


